ColDocDjango/ColDocApp/urls.py
from django.urls import path

from . import views

app_name = 'ColDoc'
urlpatterns = [
    path('<str:NICK>', views.index, name='index'),
    path('<str:NICK>/', views.index),
    path('<str:NICK>/index.html', views.index),
    path('<str:NICK>/html/<path:subpath>', views.html, name='html'),
    path('<str:NICK>/html/', views.html, name='html'),
    path('<str:NICK>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/pdfframe', views.pdfframe, name='pdfframe'),
    path('<str:NICK>/search', views.search, name='search'),
    path('<str:NICK>/check_tree', views.check_tree, name='check_tree'),
    path('<str:NICK>/postcoldocedit', views.post_coldoc_edit, name='postcoldocedit'),
    path('<str:NICK>/latex', views.latex, name='latex'),
    path('<str:NICK>/reparse', views.reparse, name='reparse'),
    path('<str:NICK>/bookindex', views.bookindex, name='bookindex'),
]

ColDocDjango/ColDocDjango/urls.py
import django
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponse

import ColDocDjango.views
from django.conf import settings
config = settings.COLDOC_SITE_CONFIG

import django.contrib.auth
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('robots.txt', ColDocDjango.views.robots_page),
    path('admin/', admin.site.urls),
    path('UUID/', include('UUID.urls')),
    path('CD/', include('ColDocApp.urls')),
    # https://docs.djangoproject.com/en/4.0/topics/i18n/translation/#the-set-language-redirect-view
    path('i18n/', include('django.conf.urls.i18n')),
    ]

if settings.USE_SIMPLE_CAPTCHA:
    urlpatterns += [
        path('captcha/', include('captcha.urls')),
    ]

if settings.USE_WALLET:
    urlpatterns += [
        path('wallet/', include('wallet.urls')),
        ]

if settings.USE_SELECT2:
    urlpatterns += [
        path('select2/', include('django_select2.urls')),
        ]

if settings.USE_ALLAUTH:
    urlpatterns += [
        path('accounts/', include('allauth.urls')),
        ]
else:
    urlpatterns.append(
        path("accounts/", include("django.contrib.auth.urls")),
    )
    #
    urlpatterns += [
    path('login/', 
         LoginView.as_view(
             template_name='account/simplelogin.html',
             extra_context={
                 'title': 'Login',
                 'site_title': config['DEFAULT']['site_name'],
                 'site_header': config['DEFAULT']['site_name']+' : Login'}),
         name="account_login"),
    path('logout/',  LogoutView.as_view(), name="account_logout"),
]

from ColDocDjango import views

urlpatterns += [
    re_path(r'^$', ColDocDjango.views.main_page, name='index'),
    path('user', views.user, name='user'),
    path('send_email', views.send_email, name='send_email'),
    ]

if isinstance(settings.GOOGLE_SITE_VERIFICATION,str):
    urlpatterns += [
        path(settings.GOOGLE_SITE_VERIFICATION, lambda r: \
             HttpResponse('google-site-verification: %s' % settings.GOOGLE_SITE_VERIFICATION,content_type='text/plain')),
        ]

ColDocDjango/UUID/urls.py
from django.urls import path

from . import views

app_name = 'UUID'
urlpatterns = [
    path('<str:NICK>/<str:UUID>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/<str:UUID>/txt', views.txt, name='txt'),
    #
    path('<str:NICK>/<str:UUID>/html/<path:subpath>', views.html),
    path('<str:NICK>/<str:UUID>/html/', views.html, name='html'),
    #
    path('<str:NICK>/<str:UUID>/show/', views.show, name='show'),
    #
    path('<str:NICK>/<str:UUID>/log/', views.log, name='log'),
    #
    path('<str:NICK>/<str:UUID>/postedit/', views.postedit, name='postedit'),
    path('<str:NICK>/<str:UUID>/postupload/', views.postupload, name='postupload'),
    path('<str:NICK>/<str:UUID>/postlang', views.postlang, name='postlang'),
    path('<str:NICK>/<str:UUID>/postmetadataedit/', views.postmetadataedit, name='postmetadataedit'),
    path('<str:NICK>/<str:UUID>/', views.index, name='index'),
    path('<str:NICK>/<str:UUID>/download', views.download, name='download'),
    path('<str:NICK>/<str:UUID>/md5/<str:ACCESS>/<path:FILE>', views.md5, name='md5'),
    path('<str:NICK>/<str:UUID>/ajax_views/', views.ajax_views, name='ajax_views'),
]

ColDocDjango/UUID/views.py
import os, sys, mimetypes, http, copy, json, hashlib, difflib, shutil, subprocess, re, io, inspect, functools, tempfile, time
from html import escape as py_html_escape
import pickle, base64
from os.path import join as osjoin

try:
    import pycountry
except:
    pycountry = None

try:
    from bs4 import BeautifulSoup
except:
    BeautifulSoup = None

try:
    from pylatexenc.latex2text import LatexNodes2Text
except:
    LatexNodes2Text = None

try:
    import magic
except:
    magic = None

try:
    import lockfile
except:
    lockfile = None


import logging
logger = logging.getLogger(__name__)


import django
from django.db import transaction
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse, QueryDict
from django.contrib import messages
from django import forms
from django.conf import settings
#from django.core import serializers
from django.core.exceptions import SuspiciousOperation, PermissionDenied
from django.utils.html import escape
from django.templatetags.static import static
from django.core.mail import EmailMessage, EmailMultiAlternatives, send_mail
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.contrib.auth.models import Group
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext, gettext_lazy, gettext_noop
from django.utils.text import format_lazy
from django.utils.functional import lazy
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

full_escape_translate_lazy = lazy ( lambda s : py_html_escape(gettext_lazy (s ) , quote=True) , str )
full_escape_lazy = lazy ( lambda s : py_html_escape(s , quote=True) , str )


if django.VERSION[0] >= 4 :
    _ = gettext_lazy
else:
    # in django 3 you cannot concatenate strings to lazy-strings
    _ = gettext

if settings.USE_SELECT2 :
    from django_select2 import forms as s2forms

    class AuthorWidget(s2forms.ModelSelect2MultipleWidget):
        search_fields = [
            "username__icontains",
            "email__icontains",
        ]
else:
    AuthorWidget = django.forms.SelectMultiple


import plasTeX.Tokenizer
import plasTeX.Base as Base
from plasTeX.TeX import TeX
#from plasTeX.Packages import graphicx

import ColDoc.utils, ColDoc.latex, ColDocDjango, ColDocDjango.users
from ColDoc.utils import slug_re, slugp_re, is_image_blob, html2text, uuid_to_dir, gen_lang_metadata, strip_delimiters
from ColDoc.utils import langc_re , lang_re
from ColDocDjango.utils import get_email_for_user, load_unicode_to_latex, check_login_timeout
from ColDoc.blob_inator import _rewrite_section, _parse_obj
from ColDoc import TokenizerPassThru, transform
from ColDocApp import text_catalog
from ColDoc.utils import iso3lang2word as iso3lang2word_untranslated
from ColDoc.utils import iso3lang2iso2
from ColDocDjango.utils import convert_latex_return_codes, latex_error_fix_line_numbers, build_hreflang_links
from ColDocDjango.middleware import redirect_by_exception

fork_class_default = ColDocDjango.utils.get_django_fork_class()

if False:
    # to debug, use a non forking class
    import coldoc_tasks.simple_tasks
    fork_class_default = coldoc_tasks.simple_tasks.nofork_class

def iso3lang2word(*v , **k):
    return gettext_lazy(iso3lang2word_untranslated(*v, **k))

def iso3lang2word_H(*v , **k):
    # do not show header 'Undetermined' or 'No linguistic content
    if v[0] in ('zxx','und'):
        return ''
    return gettext_lazy(iso3lang2word_untranslated(*v, **k))


from .models import DMetadata, ExtraMetadata, DColDoc, uuid_replaced_by

from .shop import encoded_contract_to_buy_permission, can_buy_permission

def int_(v):
    try:
        return int(v)
    except:
        logger.exception('Problem with %r',v)
    return 0


wrong_choice_list = [('internal_error','internal_error')]

##############################################################
def __redirect_other_lang(request,lang,ext):
    "  courtesy for people using other language codes "
    if lang is not None and not langc_re.match(lang) and pycountry:
        a = ColDocDjango.utils.http_to_iso_language(lang)
        if a:
            b = request.path + '?lang=' + a
            if ext:
                b += '&ext=' + ext
            logger.warning('Redirected %r %r %r to %r',request.path, lang, ext , b)
            redirect_by_exception(request.build_absolute_uri(b), permanent=True)


##############################################################

class PurchaseEncodedForm(forms.Form):
    encoded = forms.CharField(widget=forms.HiddenInput())

##############################################################

class MetadataForm(forms.ModelForm):
    class Meta:
        model = DMetadata
        fields = ['author', 'access', 'environ','optarg','latex_documentclass_choice']
        widgets = {
                    "author": AuthorWidget,
                    'environ': django.forms.Select(choices=[('invalid','invalid')])
                  }
    # record these values from submitter
    uuid_  = forms.CharField(widget=forms.HiddenInput())
    ext_  = forms.CharField(widget=forms.HiddenInput())
    lang_ = forms.CharField(widget=forms.HiddenInput(),required = False)    

###############################################################

class LangForm(forms.Form):
    UUID = forms.CharField(widget=forms.HiddenInput())
    NICK = forms.CharField(widget=forms.HiddenInput())
    ext  = forms.CharField(widget=forms.HiddenInput())
    lang = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        choice_list = kwargs.pop('choice_list')
        super(LangForm, self).__init__(*args, **kwargs)
        if kwargs.get('prefix') in ('multlang','manual'):
            if choice_list != wrong_choice_list:
                logger.error('internal inconsistency')
            self.fields['langchoice'] = forms.CharField(widget=forms.HiddenInput(),required=False)
        else:
            self.fields['langchoice'] = forms.ChoiceField(choices=choice_list,
                                                      label=_("Language"),
                                                      #help_text="Language choice"
                                                      )

    class Meta:
        fields = ('langchoice', )


# show prologue in web UI, to ease debugging
__debug_view_prologue__ = False


class BlobUploadForm(forms.Form):
    htmlid = "id_form_blobuploadform"
    file = forms.FileField(help_text=_("File to upload"))
    UUID = forms.CharField(widget=forms.HiddenInput())
    NICK = forms.CharField(widget=forms.HiddenInput())
    ext  = forms.CharField(widget=forms.HiddenInput())
    lang = forms.CharField(widget=forms.HiddenInput(),required = False)
    #oldext = forms.CharField(widget=forms.HiddenInput(),required = False)    

class BlobEditForm(forms.Form):
    #
    def __init__(self, *args, **kwargs):
        filters = kwargs.pop('latex_filters',transform.get_latex_filters())
        super().__init__(*args, **kwargs)
        for name, label, help, val, fun in filters:
            field = forms.BooleanField(label=label,required = False,widget = forms.CheckboxInput(),help_text=help, initial=val)
            self.fields[name] = field
    #
    class Media:
        js = ('UUID/js/blobeditform.js',)
    htmlid = "id_form_blobeditform"
    ## remembers first line of sections, or \uuid when present
    prologue = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-text w-75'}) \
                               if __debug_view_prologue__ else \
                               forms.HiddenInput(),
                               required = False, label=_('Prologue'),
                               help_text=_('First line of text file, automatically generated'))
    # the real blobcontent
    shortprologue = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-text w-75'}) \
                               if __debug_view_prologue__ else \
                               forms.HiddenInput(),
                               required = False, label=_('Short Prologue'),
                               help_text=_('First line of text file,  short version, automatically generated'))
    blobcontent = forms.CharField(widget=forms.HiddenInput(),required = False)
    # what the user can edit
    BlobEditTextarea=forms.CharField(label=_('Blob content'),required = False,
                                     widget=forms.Textarea(attrs={'class': 'form-text w-100'}),
                                     help_text=_('Edit the blob content'))
    BlobEditComment=forms.CharField(label=_('Comment'),required = False,
                                    widget=forms.TextInput(attrs={'class': 'form-text w-75'})
                                        if settings.USE_COMMIT_COMMENTS
                                        else forms.HiddenInput(),
                                    help_text=_('Comment for this commit'))
    UUID = forms.CharField(widget=forms.HiddenInput())
    NICK = forms.CharField(widget=forms.HiddenInput())
    ext  = forms.CharField(widget=forms.HiddenInput())
    lang = forms.CharField(widget=forms.HiddenInput(),required = False)
    file_md5 = forms.CharField(widget=forms.HiddenInput())
    selection_start = forms.CharField(widget=forms.HiddenInput(),initial=-1)
    selection_end = forms.CharField(widget=forms.HiddenInput(),initial=-1)
    split_selection = forms.BooleanField(label=_('Insert a child node'),required = False,
                                         widget = forms.CheckboxInput(attrs = {'onclick' : "hide_and_show();", }),
                                         help_text=_("Insert a child node at cursor (if a piece of text is selected, it will be moved into the child)"))
    split_environment = forms.ChoiceField(label=_("Environment"),
                                          help_text=_("Environment for newly created blob"))

ColDocDjango/UUID/templates/CodeMirrorHelp.html
<div class="nav justify-content-end">
<button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#EditHelpModal">
  Editing Help
</button>
</div>
<!-- The Modal -->
<div class="modal" id="EditHelpModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Editing Help</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <!-- Modal body -->
      <div class="modal-body">

    The  keybindings are:
    <dl>
      <dt>Ctrl-F / Cmd-F</dt><dd>Start searching</dd>
      <dt>Ctrl-G / Cmd-G</dt><dd>Find next</dd>
      <dt>Shift-Ctrl-G / Shift-Cmd-G</dt><dd>Find previous</dd>
      <dt>Shift-Ctrl-F / Cmd-Option-F</dt><dd>Replace</dd>
      <dt>Shift-Ctrl-R / Shift-Cmd-Option-F</dt><dd>Replace all</dd>
      <dt>Alt-F</dt><dd>Persistent search (dialog doesn't autoclose,
      enter to find next, Shift-Enter to find previous)</dd>
      <dt>Alt-G</dt><dd>Jump to line</dd>
      <dt>Ctrl-Space</dt><dd>Show autocompletion hint</dd>
    </dl>

      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

ColDocDjango/UUID/templates/UUID_arrows.html
 {% if uplink %}<a class="btn btn-outline-primary" href="{{uplink|safe}}">↑</a>
 {% else %}<span class="btn btn-outline-light disabled">↑</span>{% endif %}
 {% if leftlink %}<a class="btn btn-outline-primary" href="{{leftlink|safe}}">←</a>
 {% else %}<span class="btn btn-outline-light disabled">←</span>{% endif %}
 {% if rightlink %}<a class="btn btn-outline-primary" href="{{rightlink|safe}}">→</a>
 {% else %}<span class="btn btn-outline-light disabled">→</span>{% endif %}
 {% if downlink %}<a class="btn btn-outline-primary" href="{{downlink|safe}}">↓</a>
 {% else %}<span class="btn btn-outline-light disabled">↓</span>{% endif %}

ColDocDjango/UUID/templates/UUID_biblio_index.html
{% load static %}
{% load i18n %}
         {% if bibliolink %} <a href="{{ bibliolink }}"> {% translate "Bibliography" %}</a>
	 {% else %}  {% translate "Bibliography" %} {% endif %}
         {% for val,link in bibliofiles %}
                <a href="{{ link }}">  {{ val }}  </a>
		{#% if u == bibliofiles.last %} . {% else %} ; {% endif %} {% endfor #}
         {% endfor %}
	 {% if biblio_list %}
	 <ul> {% for k,v in biblio_list %} <li> [{{k}}] <span class="bg-light">{{v | safe}}</span> </li> {% endfor %} </ul>
	 {% endif %}
	 {% if biblio_list or index_list %} <br> {% else %}  —  {% endif %}
	 <a href="{% url 'ColDoc:bookindex' NICK=NICK %}{{ view_query }}"> {% translate "Book index" %}</a>
	 {% if index_list %}
	 <ul> {% for k,s,v in index_list %}
	      <li> <span class="bg-light font-italic mathjaxme">{{k}}</span> {{s}}
	           {% if v %} <span class="bg-light font-italic  mathjaxme">{{v}}</span> {% endif %}
	      </li> 
	    {% endfor %}
	 </ul>
	 {% endif %}

ColDocDjango/UUID/templates/blobeditform.html
{% load static %}
{% load i18n %}
<script>
var blob_md5="{{blob_md5}}";
{% if BLOB %}
  const get_blob_md5_url = "{% url 'UUID:md5' NICK=NICK UUID=UUID ACCESS="undefined" FILE=BLOB %}";
{% else %}
  const get_blob_md5_url = "";
{% endif %}
var      compilation_in_progress = {{ compilation_in_progress }};
const    ajax_views_url = "{{ ajax_views_url }}";
if ( compilation_in_progress ) { 
   window.addEventListener('load', ajax_views_post );
}; 
</script>


{% include "codemirror_init.html" %}

{% if USE_CODEMIRROR and perms.UUID.change_blob %}
{% include "CodeMirrorHelp.html" %}
{% endif %}

<form action="{% url 'UUID:postedit' NICK=NICK UUID=UUID %}" id="{{ blobeditform.htmlid }}" method="post" class="w-100">
         <div id="{{ blobeditform.htmlid }}_topdiv" class="bg-warning" style="display: none;">{% translate 'This content is open in another tab: do not edit here' %}</div>
        {% csrf_token %}{{ blobeditform.non_field_errors }}
        {% for field in blobeditform %} {% if field.is_hidden %}  {{ field }}
        {% elif not field.name in blobform_filters %}
         <div class="form-group w-100" id="id_div_blobeditform_{{field.name}}"  >
          {{ field.errors }}    {{ field.label_tag }} {{ field }}
          {% if field.help_text %}
            <small class="font-italic">{{ field.help_text|safe }}</small>
          {% endif %}
         </div>
        {% endif %}{% endfor %}
       {% if perms.UUID.change_blob or perms.ColDocApp.add_blob  %}
        <input type="submit" class="btn {{ compile_button_class }}"
         data-toggle="tooltip" title="Save changes, update PDF and HTML"
         onclick="update_editform();  if ( check_primary_tab() ) { prevent_unload_remove (); blob_post('compile_no_reload'); }; return false;"
         id="id_blobeditform_compile" name="compile" value="Compile">
        
        <img id="id_network_error" class="btn-danger"
             data-toggle="tooltip" title="{% translate 'There was a network error' %}"
             style="display: none;"
             src="{% static 'ColDoc/sync_problem_FILL0_wght400_GRAD0_opsz48.svg' %}"  style="height: 14pt" alt="Network error!">
       {% endif %}
        
      {% if perms.UUID.change_blob %}
         <input type="submit" class="btn btn-primary" 
         data-toggle="tooltip" title="Save changes so far, update diff"
         onclick="blob_post('save_no_reload'); return false;"
         id="id_blobeditform_save_no_reload" name="save" value="Save">

         <script>user_can_save = true;</script>

         <input type="submit" class="btn {{ revert_button_class }} float-right" 
         data-toggle="tooltip" title="Revert to previous version"
         onclick="blob_post('revert'); return false;"
         id="id_blobeditform_revert" name="revert" value="Revert">

         <br>
         <div class="border border-info mt-1 p-1">
         <input type="submit" class="btn btn-primary m-1" 
         data-toggle="tooltip" title="Normalize LaTeX"
         onclick="blob_post('normalize'); return false;"
         id="id_blobeditform_normalize" name="normalize" value="Normalize">
         
         {% for field in blobeditform %} {% if field.name in blobform_filters %}
           <span class="border bg-light text-nowrap d-inline-block m-1 pt-1" data-toggle="tooltip" title="{{ field.help_text|safe }}">
             {{ field.errors }}    {{ field.label_tag }} {{ field }}
           </span>  
          {% endif %}
         {% endfor %}

         </div>
      {% endif %}
</form>
<script>
{% if USE_CODEMIRROR  %}
$('a[href="#blob"]').on('shown.bs.tab',activate_BlobEditCodeMirror_once);
{% else %}
 {# non CodeMirror #}
window.addEventListener('load', restore_editform_non_cm );
$('#id_BlobEditTextarea').on('input propertychange change keyup paste', update_blobedit_timestamp );
{% endif %}
</script>

ColDocDjango/UUID/templates/codemirror_init.html
{% load static %}
{% load i18n %}

{% if USE_CODEMIRROR %}
<link href="{% static 'UUID/cm/lib/codemirror.css' %}" rel="stylesheet">
<link href="{% static 'UUID/cm/addon/dialog/dialog.css' %}" rel="stylesheet">
<link href="{% static 'UUID/cm/addon/search/matchesonscrollbar.css' %}" rel="stylesheet">
<link href="{% static 'UUID/cm/addon/scroll/simplescrollbars.css' %}" rel="stylesheet">
<link href="{% static 'UUID/css/cmlh.css' %}" rel="stylesheet">
<style>
      .breakpoints {width: .8em;}
      .breakpoint { color: #822; }
      .CodeMirror {border: 1px solid #aaa;}
      .cm-trailingspace {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAYAAAB/qH1jAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QUXCToH00Y1UgAAACFJREFUCNdjPMDBUc/AwNDAAAFMTAwMDA0OP34wQgX/AQBYgwYEx4f9lQAAAABJRU5ErkJggg==);
        background-position: bottom left;
        background-repeat: repeat-x;
      }
</style>
    
<script src="{% static 'UUID/cm/lib/codemirror.js' %}"></script>

<script src="{% static 'UUID/cm/mode/stex/stex.js' %}"></script>

<script src="{% static 'UUID/cm/addon/scroll/simplescrollbars.js' %}"></script>

<script src="{% static 'UUID/cm/addon/dialog/dialog.js' %}"></script>
<script src="{% static 'UUID/cm/addon/search/searchcursor.js' %}"></script>
<script src="{% static 'UUID/cm/addon/search/search.js' %}"></script>

<script src="{% static 'UUID/cm/addon/edit/matchbrackets.js' %}"></script>
<script src="{% static 'UUID/cm/addon/edit/trailingspace.js' %}"></script>

<script src="{% static 'UUID/cm/addon/scroll/annotatescrollbar.js' %}"></script>
<script src="{% static 'UUID/cm/addon/search/matchesonscrollbar.js' %}"></script>
<script src="{% static 'UUID/cm/addon/search/jump-to-line.js' %}"></script>

<script src="{% static 'UUID/cm/addon/hint/show-hint.js' %}"></script>
<script type="module" src="{% static 'UUID/js/cmlh.mjs' %}"></script>

{% endif %}