ColDocDjango/ColDocApp/urls.py
from django.urls import path

from . import views

app_name = 'ColDoc'
urlpatterns = [
    path('<str:NICK>', views.index, name='index'),
    path('<str:NICK>/', views.index),
    path('<str:NICK>/index.html', views.index),
    path('<str:NICK>/html/<path:subpath>', views.html, name='html'),
    path('<str:NICK>/html/', views.html, name='html'),
    path('<str:NICK>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/pdfframe', views.pdfframe, name='pdfframe'),
    path('<str:NICK>/search', views.search, name='search'),
    path('<str:NICK>/check_tree', views.check_tree, name='check_tree'),
    path('<str:NICK>/postcoldocedit', views.post_coldoc_edit, name='postcoldocedit'),
    path('<str:NICK>/latex', views.latex, name='latex'),
    path('<str:NICK>/reparse', views.reparse, name='reparse'),
    path('<str:NICK>/bookindex', views.bookindex, name='bookindex'),
]

ColDocDjango/ColDocDjango/urls.py
import django
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponse

import ColDocDjango.views
from django.conf import settings
config = settings.COLDOC_SITE_CONFIG

import django.contrib.auth
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('robots.txt', ColDocDjango.views.robots_page),
    path('admin/', admin.site.urls),
    path('UUID/', include('UUID.urls')),
    path('CD/', include('ColDocApp.urls')),
    # https://docs.djangoproject.com/en/4.0/topics/i18n/translation/#the-set-language-redirect-view
    path('i18n/', include('django.conf.urls.i18n')),
    ]

if settings.USE_SIMPLE_CAPTCHA:
    urlpatterns += [
        path('captcha/', include('captcha.urls')),
    ]

if settings.USE_WALLET:
    urlpatterns += [
        path('wallet/', include('wallet.urls')),
        ]

if settings.USE_SELECT2:
    urlpatterns += [
        path('select2/', include('django_select2.urls')),
        ]

if settings.USE_ALLAUTH:
    urlpatterns += [
        path('accounts/', include('allauth.urls')),
        ]
else:
    urlpatterns.append(
        path("accounts/", include("django.contrib.auth.urls")),
    )
    #
    urlpatterns += [
    path('login/', 
         LoginView.as_view(
             template_name='account/simplelogin.html',
             extra_context={
                 'title': 'Login',
                 'site_title': config['DEFAULT']['site_name'],
                 'site_header': config['DEFAULT']['site_name']+' : Login'}),
         name="account_login"),
    path('logout/',  LogoutView.as_view(), name="account_logout"),
]

from ColDocDjango import views

urlpatterns += [
    re_path(r'^$', ColDocDjango.views.main_page, name='index'),
    path('user', views.user, name='user'),
    path('send_email', views.send_email, name='send_email'),
    ]

if isinstance(settings.GOOGLE_SITE_VERIFICATION,str):
    urlpatterns += [
        path(settings.GOOGLE_SITE_VERIFICATION, lambda r: \
             HttpResponse('google-site-verification: %s' % settings.GOOGLE_SITE_VERIFICATION,content_type='text/plain')),
        ]

ColDocDjango/UUID/urls.py
from django.urls import path

from . import views

app_name = 'UUID'
urlpatterns = [
    path('<str:NICK>/<str:UUID>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/<str:UUID>/txt', views.txt, name='txt'),
    #
    path('<str:NICK>/<str:UUID>/html/<path:subpath>', views.html),
    path('<str:NICK>/<str:UUID>/html/', views.html, name='html'),
    #
    path('<str:NICK>/<str:UUID>/show/', views.show, name='show'),
    #
    path('<str:NICK>/<str:UUID>/log/', views.log, name='log'),
    #
    path('<str:NICK>/<str:UUID>/postedit/', views.postedit, name='postedit'),
    path('<str:NICK>/<str:UUID>/postupload/', views.postupload, name='postupload'),
    path('<str:NICK>/<str:UUID>/postlang', views.postlang, name='postlang'),
    path('<str:NICK>/<str:UUID>/postmetadataedit/', views.postmetadataedit, name='postmetadataedit'),
    path('<str:NICK>/<str:UUID>/', views.index, name='index'),
    path('<str:NICK>/<str:UUID>/download', views.download, name='download'),
    path('<str:NICK>/<str:UUID>/md5/<str:ACCESS>/<path:FILE>', views.md5, name='md5'),
    path('<str:NICK>/<str:UUID>/ajax_views/', views.ajax_views, name='ajax_views'),
]

ColDocDjango/ColDocApp/models.py
import os
from os.path import join as osjoin

#from datetime import datetime as DT
from django.utils import timezone as DT

from django.db import models
from django import forms
from django.core.validators  import RegexValidator
import django.core.exceptions
from django.core import serializers
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.conf import settings

# TODO : site support
# from django.contrib.sites.models import Site


import logging
logger = logging.getLogger(__name__)

from django.utils.translation import gettext, gettext_lazy, gettext_noop
_ = gettext_lazy

#############################################################

from ColDoc.utils import uuid_to_int, int_to_uuid, uuid_check_normalize, uuid_valid_symbols
from ColDoc.latex import ColDoc_latex_engines
import ColDoc.config as CC

from ColDocDjango.users import permissions_for_coldoc_extra

#####################################


## we cannot user this, it is too early
#from django.contrib.auth import get_user_model
#AUTH_USER_MODEL = get_user_model()
## su we use this
AUTH_USER_MODEL = settings.AUTH_USER_MODEL



#####################################

class UUID_FormField(forms.CharField):
    ## TODO FIXME THIS DOES NOT WORK AS EXPECTED
    default_error_messages = {
        'invalid': _('Enter a valid UUID (numbers and consonants)'),
    }
    def clean(self, value):
        if (not (value == '' and not self.required) and   not uuid_valid_symbols.match(value)):
            raise forms.ValidationError(self.error_messages['invalid'])
        return value


validate_UUID = RegexValidator(
    uuid_valid_symbols,
    # Translators: "letters" means latin letters: a-z and A-Z.
    _("Enter a valid 'UUID' consisting of numbers and consonants"),
    'invalid'
)
# https://docs.djangoproject.com/en/3.0/howto/custom-model-fields/
class UUID_Field(models.IntegerField):
    default_error_messages = {
        'invalid': _("'%(value)s' value must be a valid UUID."),
    }
    description = _("UUID")
    default_validators = [validate_UUID]
    #
    def to_python(self, value):
        if isinstance(value, str) or value is None:
            return value
        else:
            return int_to_uuid(value)
    #
    def from_db_value(self, obj, expression, connection):
        if isinstance(obj, int):
            return int_to_uuid(obj)
        elif isinstance(obj, str):
            return uuid_check_normalize(obj)
        else:
            raise ValueError(" wrong type %r"%(type(obj),))
    #
    def get_prep_value(self,value):
        if isinstance(value,int):
            return value
        assert isinstance(value,str)
        try:
            return uuid_to_int(value)
        except (TypeError, ValueError):
            raise ValidationError(
                _('Invalid UUID'),
                code='invalid',
                params={'value': value},
            )
    #
    def formfield(self, *args, **kwargs):
        return django.forms.CharField(*args, **kwargs)

# Create your models here.

COLDOC_SITE_ROOT = os.environ.get('COLDOC_SITE_ROOT')

def validate_coldoc_nickname(value):
    if value in CC.ColDoc_invalid_nickname :
        raise ValidationError(
            _('Please do not use %(value)s as nickname, it may generate confusion'),
            params={'value': value},
        )

def validate_languages(L):
    if any([ (len(z)!=3) for z in L.splitlines()]):
        raise ValidationError(  _('Malformed languages; insert one ISO_639-3 three letter code per line (and no blank lines)'), )

class DColDoc(models.Model):
    "Collaborative Document"
    #
    class Meta:
        verbose_name = "ColDoc"
        permissions = [(j,"can %s on any coldoc"%j) for j in permissions_for_coldoc_extra]
    #https://docs.djangoproject.com/en/3.0/ref/urlresolvers/#django.urls.reverse
    #https://docs.djangoproject.com/en/3.0/ref/models/instances/#django.db.models.Model.get_absolute_url
    def get_absolute_url(self):
        return reverse('ColDoc:index', args=(self.nickname,))
    #  https://docs.djangoproject.com/en/3.0/ref/models/fields
    nickname = models.SlugField("short string to identify",
                                help_text=_("short string to identify this ColDoc in URLs (alphanumeric only, use '_' or '-' for other chars)"),
                                validators=[validate_coldoc_nickname],
                                max_length=10,  db_index = True, primary_key=True)
    #
    languages = models.TextField( _("languages supported (one ISO_639-3 three letter code per line)"),
                                  validators = [validate_languages],
                                  max_length=200, blank=True)
    #
    def get_languages(self):
        " return list of languages, correctly formatted"
        L = self.languages.splitlines()
        if any([ (len(z)!=3) for z in L]):
            logger.warning('Malformed languages %r in %s', self.languages, self)
        return [z for z in L if len(z) == 3]
    #
    title = models.CharField(max_length=2000, blank=True)
    #
    ## this is obsolete. Editors are those users that are members of group coldoc_`nickname`_group_editors
    #editor = models.ManyToManyField(AUTH_USER_MODEL)
    #
    abstract = models.TextField(max_length=10000, blank=True)
    #
    publication_time = models.DateTimeField('time first published', default=DT.now)
    #
    ## TODO
    #modification_time = models.DateTimeField('time of last modification', default=DT.now)
    #def modification_time_update(self, default=None):
    #    if default is None: default=DT.now()
    #    self.modification_time = default
    #
    blob_modification_time = models.DateTimeField(_('time of last modification of any blob in this coldoc'), default=DT.now)
    def blob_modification_time_update(self, default=None):
        if default is None: default=DT.now()
        self.blob_modification_time = default
        self.save()
    #
    latex_time = models.DateTimeField(_('time of last run of latex'),
                                      default=None, null=True, blank=True)
    def latex_time_update(self, default=None):
        if default is None: default=DT.now()
        self.latex_time = default
        self.save()
    #
    # see description in the `permission` section of the documentation
    latex_macros_private = models.TextField(max_length=1000, blank=True,
                                            default=CC.ColDoc_latex_macros_private)
    latex_macros_public = models.TextField(max_length=1000, blank=True,
                                            default=CC.ColDoc_latex_macros_public)
    latex_macros_uuid = models.TextField(max_length=1000, blank=True,
                                            default=CC.ColDoc_latex_macros_uuid)
    graphic_template  = models.TextField(max_length=1000, blank=True,
                                            default=CC.ColDoc_graphic_template)
    graphic_mul_template  = models.TextField(max_length=1000, blank=True,
                                            default=CC.ColDoc_graphic_mul_template)
    #
    # blank means that no error occoured
    latex_return_codes = models.CharField(max_length=2000, blank=True)
    #
    anonymous_can_view = models.BooleanField(default=True)
    #
    pdflatex_fortify = models.BooleanField(_('add some parameters to `pdflatex` to fortify againsta hacks; disable only if you trust your users (and you wish to use `imakeidx`)'),
                                           default=True)
    #
    author_can_add_blob = models.BooleanField(_('An user can add a child node if s/he is the author of the blob'),default=True)
    #
    LATEX_ENGINES=ColDoc_latex_engines
    latex_engine = models.CharField(_("latex-type command used to compile"),
        max_length=15,
        choices=LATEX_ENGINES,
        default='pdflatex',
    )
    #
    root_uuid = UUID_Field(default=1)
    #
    def save(self):
        ## TODO should update only if something was changed.. use signals?
        #try:
        #    self.modification_date_update()
        #except:
        #    logger.exception()
        r = super().save()
        if COLDOC_SITE_ROOT is None:
            raise RuntimeError("Cannot save, COLDOC_SITE_ROOT==None: %r",self)
        coldoc_dir = osjoin(COLDOC_SITE_ROOT,'coldocs',self.nickname)
        if not os.path.exists(coldoc_dir):
            os.makedirs(coldoc_dir)
        data = serializers.serialize("json", [self])
        assert data[0] == '[' and data[-1]==']'
        with open(osjoin(coldoc_dir,'coldoc.json'),'w') as f_:
            f_.write(data[1:-1])
    #
    #def get_fields(self):
    #    return [(field.name, field.value_to_string(self)) for field in DColDoc._meta.fields]
    #### making these customizable is overkill and useless
    #
    #def base_path(s):
    #    return osjoin(COLDOC_SITE_ROOT,s.nickname)
    #base_path = osjoin(COLDOC_SITE_ROOT,'coldoc')
    #
    #git_master_dir = models.FilePathField("directory for the `git` bare repository",
    #                                      path=base_path, default='git',
    #                                      allow_folders = True, allow_files = False)
    #blobs_user_dirs = models.FilePathField("directory under which the `git` bare repository is checked out, for each user wishing to modify it",
    #                                        path=base_path, default='users',
    #                                        allow_folders = True, allow_files = False)
    #blobs_anon_dir = models.FilePathField("directory where the `git` bare repository is checked out, but masking private blobs",
    #                                      path=base_path, default='anon',
    #                                      allow_folders = True, allow_files = False)

ColDocDjango/ColDocApp/templates/bookindex.html
{% extends "bootstrapbase.html" %}
{% load i18n %}
{% block title %} {% translate 'book index' %} — {{ coldoc.nickname }} — ColDoc{% endblock %}
{% block content %}

<h1>{% if coldoc.title %} {{coldoc.title}} {% else %}
ColDoc  — {{ coldoc.nickname }} {% endif %} —
{% translate 'book index' %}
</h1>

{% if index %}
 {% for lang3, language, subindex in index %}
   <h2>   {{ language }}   </h2>
    <ul>
    {% for sortkey, key, uuids in subindex %}
        <li>
        <span {% if sortkey %}data-toggle="tooltip" title="{{ sortkey }}"{%endif%} class="bg-light {{ keyclass }}"> {{key}} </span>,
        {% for uuid, marker, refkey, text_class, fullkey in uuids %}
            <a href="{% url 'UUID:index' NICK=coldoc.nickname UUID=uuid %}" 
               {% if fullkey %} data-toggle="tooltip" title="{{ fullkey }}" {%endif%}>
             <span class="{{ text_class }}">{{ marker }}</span>
             {% if refkey %}<span class="mathjaxme">{{ refkey }}</span>{% endif %}
            </a>
            {% if marker != '—' %}{% if forloop.last %}.{% else %},{%endif%}{%endif%}
        {% endfor %}
        </li>
    {% endfor %}
    </ul>
   {% if n_languages_after_merge > 1 and lang3 %}
   <a href="{% url 'ColDoc:bookindex' NICK=coldoc.nickname %}?lang={{ lang3 }}"  class="btn  btn-outline-primary btn-sm">
   {% blocktranslate %}Show only {{ language }}.{% endblocktranslate %}   </a>
   {% endif %}
  {% endfor %}

   {% if n_languages_before_merge > 1 and n_languages_after_merge <= 1 %}
   <a href="{% url 'ColDoc:bookindex' NICK=coldoc.nickname %}"  class="btn  btn-outline-primary btn-sm">
   {% translate 'Show index broken down by language' %}</a>
   {% endif %}


{% else %}
    <p><i>{% translate 'The index is empty.' %}</i></p>
{% endif %}


{% endblock %}

ColDocDjango/ColDocApp/templates/coldoc.html
{% extends "bootstrapbase.html" %}
{% load i18n %}
{% load static %}
{% load tz %}
{% block title %} {{ coldoc.nickname }} — ColDoc{% endblock %}
{% block extrahead %}<script src="{% static 'ColDoc/js/dyna.js' %}"></script>{% endblock %}
{% block content %}


<h1>{% if coldoc.title %} {{coldoc.title}} {% else %}
ColDoc  — {{ coldoc.nickname }} {% endif %}</h1>

{% translate "First published" %}
{{ coldoc.publication_time  | localtime }}
{{ coldoc.publication_time  | localtime |  date:"e"}}
<br>
{% translate "Last updated" %}
{{ coldoc.blob_modification_time  | localtime }}
{{ coldoc.blob_modification_time  | localtime  | date:"e"}}


{% if coldoc.authors %}
<h2>{% translate "Authors" %}</h2>
<p> {{ coldoc.authors|escape|linebreaks }}</p>
{% endif %}
{% if coldoc.abstract %}
<h2>Abstract</h2>
<p>{{ coldoc.abstract }}</p>
{% endif %}

<br>

<a href="{% url 'ColDoc:html' NICK=coldoc.nickname %}" class="btn {{ whole_button_class }} btn-sm">
 {% translate "View whole document" %}
</a>

<a href="{% url 'ColDoc:pdfframe' NICK=coldoc.nickname %}#titlebeforepdf" class="btn {{ whole_button_class }} btn-sm">
 {% translate "View whole document, as PDF" %}
</a>

<a href="{% url 'UUID:index' NICK=coldoc.nickname UUID=coldoc.root_uuid %}" class="btn btn-outline-primary btn-sm">
 {% translate "Navigate document tree" %}
</a>

<br>

{% if user.is_editor %}
<a href="{% url 'ColDoc:latex' NICK=coldoc.nickname %}?type=anon"
 class="btn btn-outline-primary btn-sm" data-toggle="tooltip" 
 title="{% translate 'Compile whole document. In this HTML and PDF private material is omitted.' %}">
 {% translate "Compile public" %} 
</a>
<a href="{% url 'ColDoc:latex' NICK=coldoc.nickname  %}?type=main" class="btn btn-outline-primary btn-sm" data-toggle="tooltip" 
 title="{% translate 'Compile whole document. This HTML and PDF are visible only to editors; all material is visible.' %}">
 {% translate "Compile private" %}
</a>
<a href="{% url 'ColDoc:latex' NICK=coldoc.nickname  %}?type=tree" class="btn btn-outline-primary btn-sm"
 data-toggle="tooltip" title="{% translate 'Recompile HTML and PDF for all blobs.' %}">
 {% translate "Compile blobs" %}
</a>
<a href="{% url 'ColDoc:reparse' NICK=coldoc.nickname  %}" class="btn btn-outline-primary btn-sm"
 data-toggle="tooltip" title="{% translate 'Reparse all blobs to extract metadata.' %}">
 {% translate "Reparse" %}
</a>
{% endif %}

<!-- <a href="{{ htmlurl }}?download"><button type="button" class="btn btn-outline-primary btn-sm">Download</button></a>    <br> -->

<!-- <h2>View</h2> <iframe src="{{ htmlurl }}"   width="100%"   height="640px">(View should be displayed here)</iframe> -->



<ul class="nav nav-tabs" id="myTab" role="tablist">
 {% if user.is_editor %}
  <li class="nav-item">
    <a class="nav-link" id="status-tab" data-toggle="tab" href="#status" role="tab" aria-controls="status" aria-selected="true">
    {% translate "Status" %}</a>
  </li>
 {% endif %}
 {% if  user.is_staff or perms.ColDocApp.view_dcoldoc %}
  <li class="nav-item">
      <a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false">
      {% translate "Settings" %}</a>
  </li>
 {% endif %}
  {% if perms.UUID.view_log %}
  <li class="nav-item">
    <a class="nav-link" id="logs-tab" data-toggle="tab" href="#logs" role="tab" aria-controls="logs" aria-selected="false">
    {% translate "Logs" %}</a>
  </li>
 {% endif %}
 {% if  USE_BACKGROUND_TASKS and user.is_editor %}
  <li class="nav-item">
    <a class="nav-link" id="tasks-tab" data-toggle="tab" href="#tasks" role="tab" aria-controls="tasks" aria-selected="false">
    {% translate "Tasks" %}</a>
  </li>
 {% endif %}
</ul>



<div class="tab-content" id="myTabContent">

{% if user.is_editor %}
<div class="tab-pane fade show active border m-2 p-1" id="status" role="tabpanel" aria-labelledby="status-tab">
<h2>{% translate "Document checks" %}</h2>
<div class="border border-info m-2 p-1">
<div id='id_check_tree'>......</div>
<button   type="button" class="btn btn-outline-primary btn-sm" id="id_button_check_tree" onClick="AJAXcheck_tree('{{ check_tree_url }}');">
  {% translate "Check tree" %}
</button>
</div>
<script>
const check_tree_url = '{{ check_tree_url }}';
window.addEventListener("load", (event) => {
   AJAXcheck_tree(check_tree_url);
 });
</script>

<div id="id_latex_error_logs" class="border border-info mt-2">
{% include "latex_error_logs.html" %}
</div>

{% if failedblobs %}
<h2>{% translate "Failed blobs in tree" %}</h2>
<ul>
 {% for val ,link in failedblobs %}
 <li>{% if link  %}  <a href="{{ link }}">    {% endif %}
                {{ val }}
                {% if link %}  </a>   {% endif %}
{% endfor %}
</ul>
{% endif %}
</div> <!-- div view -->
{% endif %} <!-- if editor-->


<div class="tab-pane fade show border m-2 p-1" id="settings" role="tabpanel" aria-labelledby="settings-tab">
{% if perms.ColDocApp.view_dcoldoc %}
<h2>{% translate "Settings" %}</h2>
<div class="border border-info m-2 p-1">
     {% if perms.ColDocApp.change_dcoldoc %}
     <form action="{% url 'ColDoc:postcoldocedit' NICK=NICK %}" id="{{ coldocform.htmlid }}" method="post" class="w-100">
     {% csrf_token %}{{ coldocform.non_field_errors }}
     {% endif %}
<table class="w-100">{{ coldocform }}</table>
{% if perms.ColDocApp.change_dcoldoc %} <input type="submit" class="btn btn-primary" value="Submit">   </form> {% else %}
   <div class="alert alert-warning" role="alert">{% translate "No permission to change data." %}</div>{% endif %}
</div>
{% endif %} <!--perms.ColDocApp.view_dcoldoc-->

{% if user.is_staff %}
<a href="/admin/ColDocApp/dcoldoc/{{ coldoc.nickname }}/change/" class="btn btn-outline-primary btn-sm">
  {% translate "edit settings in admin form" %}
</a>
{% endif %}
</div>  <!-- settings tab -->

 {% if perms.UUID.view_log %}
  <div class="tab-pane fade" id="logs" role="tabpanel" aria-labelledby="logs-tab">
    <div class="row">
    {% for val1,availablelogs2 in availablelogs %}
      <div class="col">
       <h3>{{ val1 }}</h3>
       <ul>
       {% for val2,link in availablelogs2 %}
                <li>{% if link  %}  <a href="{{ link }}">    {% endif %}
                {{ val2 }}
                {% if link %}  </a>   {% endif %}
		</li>
      {% endfor %}
       </ul>
      </div>
    {% endfor %}
    </div>
  </div>
 {% endif %}
 

{% if  USE_BACKGROUND_TASKS and user.is_editor %}
 <div class="tab-pane fade show border m-2 p-1" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
<h2>{% translate "Tasks" %}</h2>
<div class="row border border-info m-2 p-1"> 
{% for val in tasks %}
 <table class="col sm border border-info m-1 p-1">{{ val }} </table>
{% endfor %}
</div>
<h2>{% translate "Completed Tasks" %}</h2>
<div class="row border border-info m-2 p-1"> 
{% for val in completed_tasks %}
 <table class="col sm border border-info m-1 p-1">{{ val }} </table>
{% endfor %}
</div>
</div> <!-- view tab -->
{% endif %} <!-- if editor etc -->

</div> <!--class="tab-content" id="myTabContent"-->

{% endblock %}

ColDocDjango/ColDocApp/templates/pdfframe.html
{% extends "bootstrapbase.html" %}
{% load static %}
{% load i18n %}

{% block extrahead %}
<script>
var view_md5="{{view_md5}}";
const get_view_md5_url = "{% url 'UUID:md5' NICK=NICK UUID=UUID ACCESS=ACCESS FILE=FILENAME %}";
</script>
<script src="{% static 'UUID/js/notifychange.js' %}"></script>
{% endblock %}
{% block title %} {{ NICK  }} — PDF — ColDoc{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center min-vh-100">
    <div class="col">
      <div class="d-flex flex-column h-100">
        <div class="row justify-content-center">
        <a name="titlebeforepdf"> Coldoc  {{ NICK  }} — 
	    &nbsp;  {% translate  'Language' %}  &nbsp;
	    {% if LANGUAGES %}
	    <span class="dropdown">
	      <a class="dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		{{ LANGUAGE }}
	      </a>
	      <div class="dropdown-menu">
		{% for name,url in LANGUAGES %}
		<a class="dropdown-item" href="{{url | safe}}">{{ name }}</a>
		{% endfor %}
	      </div>
	    </span>
	    {% else %}
	    {{ LANGUAGE }}
	    {% endif %}
	    &nbsp; — &nbsp;   {% translate  'Access' %}
	    {{ ACCESS }}
	  </a>
        </div>
        <div class="row justify-content-center flex-grow-1">
          <object data="{{ pdfurl | safe }}" type="application/pdf" class="h-100 w-100" id="id_pdf_object">
            <iframe src="{{ pdfurl | safe }}" class="h-100 w-100"></iframe>
            <!--<iframe src="https://docs.google.com/viewer?url=your_url_to_pdf&embedded=true"></iframe>-->
          </object>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$( document ).ready(function() {
    $('#id_pdf_object').focus();
});
</script>
{% endblock %}