ColDocDjango/ColDocApp/urls.py
from django.urls import path

from . import views

app_name = 'ColDoc'
urlpatterns = [
    path('<str:NICK>', views.index, name='index'),
    path('<str:NICK>/', views.index),
    path('<str:NICK>/index.html', views.index),
    path('<str:NICK>/html/<path:subpath>', views.html, name='html'),
    path('<str:NICK>/html/', views.html, name='html'),
    path('<str:NICK>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/pdfframe', views.pdfframe, name='pdfframe'),
    path('<str:NICK>/search', views.search, name='search'),
    path('<str:NICK>/check_tree', views.check_tree, name='check_tree'),
    path('<str:NICK>/postcoldocedit', views.post_coldoc_edit, name='postcoldocedit'),
    path('<str:NICK>/latex', views.latex, name='latex'),
    path('<str:NICK>/reparse', views.reparse, name='reparse'),
    path('<str:NICK>/bookindex', views.bookindex, name='bookindex'),
]

ColDocDjango/ColDocDjango/urls.py
import django
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponse

import ColDocDjango.views
from django.conf import settings
config = settings.COLDOC_SITE_CONFIG

import django.contrib.auth
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('robots.txt', ColDocDjango.views.robots_page),
    path('admin/', admin.site.urls),
    path('UUID/', include('UUID.urls')),
    path('CD/', include('ColDocApp.urls')),
    # https://docs.djangoproject.com/en/4.0/topics/i18n/translation/#the-set-language-redirect-view
    path('i18n/', include('django.conf.urls.i18n')),
    ]

if settings.USE_SIMPLE_CAPTCHA:
    urlpatterns += [
        path('captcha/', include('captcha.urls')),
    ]

if settings.USE_WALLET:
    urlpatterns += [
        path('wallet/', include('wallet.urls')),
        ]

if settings.USE_SELECT2:
    urlpatterns += [
        path('select2/', include('django_select2.urls')),
        ]

if settings.USE_ALLAUTH:
    urlpatterns += [
        path('accounts/', include('allauth.urls')),
        ]
else:
    urlpatterns.append(
        path("accounts/", include("django.contrib.auth.urls")),
    )
    #
    urlpatterns += [
    path('login/', 
         LoginView.as_view(
             template_name='account/simplelogin.html',
             extra_context={
                 'title': 'Login',
                 'site_title': config['DEFAULT']['site_name'],
                 'site_header': config['DEFAULT']['site_name']+' : Login'}),
         name="account_login"),
    path('logout/',  LogoutView.as_view(), name="account_logout"),
]

from ColDocDjango import views

urlpatterns += [
    re_path(r'^$', ColDocDjango.views.main_page, name='index'),
    path('user', views.user, name='user'),
    path('send_email', views.send_email, name='send_email'),
    ]

if isinstance(settings.GOOGLE_SITE_VERIFICATION,str):
    urlpatterns += [
        path(settings.GOOGLE_SITE_VERIFICATION, lambda r: \
             HttpResponse('google-site-verification: %s' % settings.GOOGLE_SITE_VERIFICATION,content_type='text/plain')),
        ]

ColDocDjango/UUID/urls.py
from django.urls import path

from . import views

app_name = 'UUID'
urlpatterns = [
    path('<str:NICK>/<str:UUID>/pdf', views.pdf, name='pdf'),
    path('<str:NICK>/<str:UUID>/txt', views.txt, name='txt'),
    #
    path('<str:NICK>/<str:UUID>/html/<path:subpath>', views.html),
    path('<str:NICK>/<str:UUID>/html/', views.html, name='html'),
    #
    path('<str:NICK>/<str:UUID>/show/', views.show, name='show'),
    #
    path('<str:NICK>/<str:UUID>/log/', views.log, name='log'),
    #
    path('<str:NICK>/<str:UUID>/postedit/', views.postedit, name='postedit'),
    path('<str:NICK>/<str:UUID>/postupload/', views.postupload, name='postupload'),
    path('<str:NICK>/<str:UUID>/postlang', views.postlang, name='postlang'),
    path('<str:NICK>/<str:UUID>/postmetadataedit/', views.postmetadataedit, name='postmetadataedit'),
    path('<str:NICK>/<str:UUID>/', views.index, name='index'),
    path('<str:NICK>/<str:UUID>/download', views.download, name='download'),
    path('<str:NICK>/<str:UUID>/md5/<str:ACCESS>/<path:FILE>', views.md5, name='md5'),
    path('<str:NICK>/<str:UUID>/ajax_views/', views.ajax_views, name='ajax_views'),
]

ColDocDjango/templates/analytics.html
 {% if GOOGLE_ANALYTICS4 %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS4 }}"></script>
<script defer>
"use strict";
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '{{ GOOGLE_ANALYTICS4 }}');
// https://developers.google.com/tag-platform/devguides/consent
gtag('consent', 'default', {
       // currently there are no ads
       'ad_storage': 'denied',
       'analytics_storage': 'denied'
     });

var COLDOC_COOKIE_CONSENT_VALUE = Cookies.get(COLDOC_COOKIE_CONSENT_NAME);

// the Do Not Track feature is mostly abandonware but still we may use
// https://en.wikipedia.org/wiki/Do_Not_Track
var Do_Not_Track = navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack;

if ( COLDOC_COOKIE_CONSENT_VALUE == undefined && Do_Not_Track == 1) {
  Cookies.set(COLDOC_COOKIE_CONSENT_NAME, 0, { expires : 90 });
  COLDOC_COOKIE_CONSENT_VALUE = 0;
};

function google_analytics_update_consent() {
  CONSENT_VALUE = Cookies.get(COLDOC_COOKIE_CONSENT_NAME);
  if ( CONSENT_VALUE == undefined ) {
     // maybe it is not ready...
     setTimeout(google_analytics_update_consent, 500);
  } else {
    // update global variable as well
    COLDOC_COOKIE_CONSENT_VALUE = CONSENT_VALUE;
    // update GA settings
    analytics_storage =  (CONSENT_VALUE == 1 )? 'granted' : 'denied';
    consent = {
       // currently there are no ads
       'ad_storage': 'denied',
       'analytics_storage':  analytics_storage
     };
     gtag('consent', 'update', consent);
 };
};




if ( COLDOC_COOKIE_CONSENT_VALUE == undefined ) {
    setTimeout( () => { $('#CookieModal').modal('show'); cookieModal_update_icon(-5); } , 3500);
} else { 
    google_analytics_update_consent();
};
</script>
{% else %}
<script>
function google_analytics_update_consent() {};
</script>
{% endif %}

ColDocDjango/templates/base.html
bootstrapbase.html

ColDocDjango/templates/bootstrapbase.html
{% load static %}{% load i18n %}<!doctype html>
<html lang="{{ request.LANGUAGE_CODE }}">
  <head>
    <!-- Required meta tags -->
    {% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% for lang_ , url_ in hreflanglinks %}
     <link rel="alternate" hreflang="{{ lang_ }}"  href="{{ url_  | safe }}" />
    {% endfor %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- plasTeX CSS -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <!-- js.cookie -->
    <script src="{% static 'ColDoc/js/js.cookie.js' %}"></script>
    <!--and eventually MathJax-->
  <script>
  // render mathjax only where the class contains 'mathjaxme', and async
  MathJax = {
      tex: {  tags: 'ams' ,}, // should be 'ams', 'none', or 'all'
      startup: {  elements: null , typeset: false , ready: mathjaxall, },
      tex2jax: {inlineMath: [ ['\\(','\\)'] ] },
  };

  async function mathjaxall () {
	MathJax.startup.defaultReady();
	var arr = [...document.querySelectorAll('.mathjaxme')]; MathJax.typeset(arr ); console.log('mathjax rendered ', arr.length, ' nodes');
    };
    
  var COLDOC_COOKIE_CONSENT_NAME = 'coldoc_cookie_consent';
  
  var user_can_save = false;
  const session_expiry_age  = {{ session_expiry_age }};
  const session_expiry_time = {{ session_expiry_time }};
  var session_expired_p = false;
  const alert_expiry_message = "{% translate 'The session has timed out; you should login again.' %}";
  const alert_expiry_save_message = "{% translate 'The session will timeout soon; content has been saved; you should login again.' %}";
  </script>
  <script src="{% static 'ColDoc/js/session.js' %}"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <style>
      .checkbeforetext:before {
        content: '\2713';
        display: inline-block;
	color: red;
        padding: 0 6px 0 0;
       }
       .errorlist {background-color: #fff0f0;}

       body {
	display: flex;
	min-height: 100vh;
	flex-direction: column;
      }

      main {
	flex: 1;
      }
    </style>
    {% include "analytics.html" %}
    {% endblock head %}
    {% block extrahead %}{% endblock extrahead %}
    {% include "extrahead.html" %}
  </head>
  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
  <img src="{% static "ColDoc/ColDoc_logo.png" %}" alt="ColDoc Logo">
  {% block navbarbrand %}ColDoc{% endblock %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index'  %}">Admin</a>
      </li>
      {% endif %} {# user.is_authenticated #}


      </ul>
      <ul class="navbar-nav">
   	{% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	  <span data-toggle="tooltip" title="{% translate 'Successfully logged in' %}">  😀 </span>
	  {% if user.is_author %} <span data-toggle="tooltip" title="{% translate 'Author' %}"> ✎ </span> {% endif %}
	  {% if user.is_editor %} <span data-toggle="tooltip" title="{% translate 'Editor' %}"> 🎩 </span>  {% endif %}
	  {% if user.is_staff %}  <span data-toggle="tooltip" title="{% translate 'Staff' %}"> 🔧 </span> {% endif %}
	  {{ user.get_username }} 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	  {% if USE_ALLAUTH %}
	   <a class="dropdown-item" href="{% url 'account_email' %}">{% translate 'Email' %}</a>
	   <a class="dropdown-item" href="{% url 'account_change_password' %}">{% translate 'Change password' %}</a>
	   <a class="dropdown-item" href="{% url 'account_reset_password' %}">{% translate 'Reset password' %}</a>
	   <a class="dropdown-item" href="{% url 'socialaccount_connections' %}">{% translate 'Social connections' %}</a>
	  {% else %} {# USE_ALLAUTH #}
	   <a class="dropdown-item" href="{% url 'password_change' %}">{% translate 'Change password' %}</a>
	  {% endif %} {# USE_ALLAUTH #}
	  {% if USE_WALLET %}
	   	  <a class="dropdown-item" href="{% url 'wallet:show' %}">Wallet</a>
          {% endif %} {# USE_WALLET #}
	  <a class="dropdown-item" href="{% url 'account_logout' %}">{% translate 'Logout' %}</a>
        </div>
      </li>
      {% else %} {# user.is_authenticated #}
      <li class="nav-item active">
      <a class="dropdown-item" href="{% url 'account_login'  %}?next={{ request.get_full_path  }}"> 😑  Login</a>  
      </li>
    {% endif %} {# user.is_authenticated #}
     </ul>
     
   {% if NICK is not None %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'ColDoc:search' NICK=NICK %}" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="searchtoken" 
      {% if searchpreset %} value="{{ searchpreset }}" {% else %}  placeholder="Search" {% endif %} aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0"  type="submit">Search</button>
    </form>
    {% endif %}
  </div>
</nav>

</header>

 <div id="id_messages" aria-live="polite" aria-atomic="true"  class="sticky-top" style="position: absolute; top: 20px; right: 20px;">
 {% include 'messages.html' %}
</div>
 <main class="{{ MAIN_CONTAINER_CLASS | default:"container" }}" >
    <!-- Content here -->
        {% block content %}fake content{% endblock %}
 </main>
 <footer class="bg-light">
  <span  class="text-muted">
   <a href="https://github.com/mennucc/ColDoc_project">The <i>ColDoc</i> document management system</a> is 
   Copyright 2019-23 <a href="https://www.sns.it/it/persona/andrea-carlo-giuseppe-mennucci">A. Mennucci</a>
  </span>
  <span  class="container text-muted">
       |
      Quality control
       <a href="https://validator.w3.org/nu/?doc={{ request.build_absolute_uri | urlencode }}" class="text-muted">HTML 5</a>
       | 
      <a href="https://jigsaw.w3.org/css-validator/validator?uri={{ request.build_absolute_uri | urlencode }}" class="text-muted">CSS 2.1</a>
       |
       {% get_current_language as LANGUAGE_CODE %}
       Interface language: {{ LANGUAGE_CODE|language_name_local }}
       <button type="button" class="btn btn-sm btn-outline-success my-0 my-sm-0" data-toggle="modal" data-target="#languageModal">
         Change
      </button>
      |
      <button type="button" class="btn btn-sm btn-outiline-success my-0 my-sm-0" data-toggle="modal"
        onclick="cookieModal_update_icon(-1);" data-target="#CookieModal">
        Privacy settings
      </button>
  </span>
  {% include "language_choice_modal.html" %}
  {% include "cookie_modal.html" %}
   </footer>

    <!-- Optional JavaScript -->
    <script>
    $(function () { $('[data-toggle="tooltip"]').tooltip()});
    // Javascript to enable link to tab,  https://stackoverflow.com/a/9393768/5058564
    var url = document.location.toString();
    if (url.match('#')) {
      $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
    } 
    // Change hash for page-reload
    $('.nav-tabs a').on('shown.bs.tab', function (e) {
       window.location.hash = e.target.hash;
    })
    // 
    $('.toast').toast("show");
</script>
  </body>
</html>

ColDocDjango/templates/cookie_modal.html
{% load i18n %}
<script>
function cookieModal_update_icon(val) {
 if ( val == -1 ) { 
  val = Cookies.get(COLDOC_COOKIE_CONSENT_NAME);
 }
 if ( val == 1 ){
    $("#cookieModalAllow").addClass("checkbeforetext");
    $("#cookieModalDeny").removeClass("checkbeforetext");
 } else { if ( val == 0 ){
    $("#cookieModalAllow").removeClass("checkbeforetext");
    $("#cookieModalDeny").addClass("checkbeforetext");
   } else {
    $("#cookieModalAllow").removeClass("checkbeforetext");
    $("#cookieModalDeny").removeClass("checkbeforetext");
   }};
};
</script>
<div class="modal" id="CookieModal" role="dialog" aria-labelledby="cookieModalLabel" aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
   <!-- Modal Header -->
   <div class="modal-header">
    <h4 class="modal-title" id="cookieModalLabel">Privacy settings</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
   </div>
   <!-- Modal body -->
   <div class="modal-body">
    <span>This site uses cookies to store preferences and for anonymouse usage statistics. See
    <a href="/privacy.html" class="ml-1 text-decoration-none">Privacy policy</a> </span>
    <div class="mt-2 d-flex align-items-center justify-content-center g-2">
     <button  class="btn btn-success" data-dismiss="modal" id="cookieModalAllow"
      onclick="Cookies.set(COLDOC_COOKIE_CONSENT_NAME, 1, { expires : 90 });google_analytics_update_consent();" >Allow tracking cookies</button>
     <button  class="btn btn-primary" data-dismiss="modal" id="cookieModalDeny"
      onclick="Cookies.set(COLDOC_COOKIE_CONSENT_NAME, 0, { expires : 90 });google_analytics_update_consent();" >Deny tracking cookies</button>
    </div>
   </div>
  </div>
 </div>
</div>

ColDocDjango/templates/extrahead.html
<!-- extra headers specific for this portal -->

ColDocDjango/templates/index.html
{% extends "bootstrapbase.html" %}
{% load i18n %}
{% block title %}{% translate 'home' %} — ColDoc{% endblock %}
{% block content %}


<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="coldocs-tab" data-toggle="tab" href="#coldocs" role="tab" aria-controls="coldocs" aria-selected="true">Coldocs</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="about-tab" data-toggle="tab" href="#about" role="tab" aria-controls="about" aria-selected="true">About</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="coldocs" role="tabpanel" aria-labelledby="coldocs-tab">
    <h2>ColDocs</h2>

    <ul>
      {% for object in DColDocs %}
      <li> <a href="{% url 'ColDoc:index' object.nickname %}">
	  <h3>{% if object.title %} {{ object.title }} {% else %} Coldoc — {{  object.nickname }} {% endif %}</h3>
	</a>
	<!-- <ul> -->
	<!--   {% for key, val in object.get_fields %} -->
	<!--   <li>{{ key }}: {{ val }}</li> -->
	<!--   {% endfor %} -->
	  <!-- </ul> -->
      </li>
      {% endfor %}
    </ul>

  </div>
  <div class="tab-pane fade show" id="about" role="tabpanel" aria-labelledby="about-tab">
    <h2>About</h2>
    <h3>What</h3>
    A <i>ColDoc</i> is a collaborative document.

    <h3>Why</h3>
    
    There are two main frameworks currently used to present information (in particular,
    related to scientific fields).
    <ul><li>A document redacted with the standard <i>LaTeX</i>/<i>PDF</i>
	toolbox. <i>Pros:</i> these documents are state-of-the-art quality.
	<i>Cons:</i>
	the final user has no way of interacting with a PDF document
	(other than sending an e-mail to the original authors)</li>
      <li>The <i>Web 2.0</i> way  (think of:
	<a href="https://www.wikipedia.org/"><i>Wikipedia</i></a>,
	<a href="https://en.wikipedia.org/wiki/Stack_Exchange"><i>Stack Exchange</i></a>...).
	<i>Pros:</i>	in those frameworks, content is continuously developed and augmented by users.
	<i>Cons:</i> the end result, though, is fragmented, and cannot (in general) be presented as an unified document.
	</li>
    </ul>

    A ColDoc tries to get the best of two publishing frameworks.

    <h3>How</h3>

    The <i>ColDoc</i> project is still in its infancy; the source code is available for anyone to help.
  </div>
</div>

{% endblock %}

ColDocDjango/templates/language_choice_modal.html
{% load i18n %}
<!--https://getbootstrap.com/docs/4.3/components/modal/-->

<div class="modal fade" id="languageModal" tabindex="-1" role="dialog" aria-labelledby="languageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="languageModalLabel">Interface language</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form action="{% url 'set_language' %}" method="post">
      {% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }} ({{ language.code }})
          </option>
        {% endfor %}
      </select>
      <input type="submit" class="btn btn-primary" value="Go">
      </form>
      </div>
      <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

ColDocDjango/templates/latex_error_logs.html
{% if latex_error_logs %}
    There were errors while compiling
    <ul>
        {% for e_program, e_lang, e_access, e_extension, e_link, e_errors in latex_error_logs %}
         <li>{% if e_link  %}  <a href="{{ e_link }}">    {% endif %}
         {{ e_program }} {{ e_lang}}  {{ e_access }}
         {% if e_link %}  </a>   {% endif %}
         {% if e_errors %}
            <ul class="border  border-info mt-2">
            {% for e_uuid, e_line, e_text in e_errors %}
            <li><a href="{% url 'UUID:index' NICK=NICK UUID=e_uuid  %}#blob"> uuid {{ e_uuid }}</a>
              line {{ e_line }} <code class="container-flex">{{ e_text | linebreaksbr }}</code>
            {% endfor %}
            </ul>
         {% endif %}
        {% endfor %}
    </ul>
{% endif %}

ColDocDjango/templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="toast notification border-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}"
          role="alert" aria-live="polite" aria-atomic="true"   data-delay="25000">
        <div class="toast-header">
            <strong class="mr-auto">
                {{message.tags|capfirst}}
            </strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"
                    onclick="$(this).closest('.toast').remove()">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            {{message|safe}}
        </div>
    </div>
{% endfor %}
{% endif %}

ColDocDjango/templates/user.html
{% extends "bootstrapbase.html" %}
{% block title %}User {{ thatuser }} — ColDoc{% endblock %}
{% block content %}


<h1>User {{ thatuser }}</h1>
    
<h2>Information</h2>

<table class="table table-bordered table-sm table-hover">
  <tr> <th>first_name </th> <td>{{ thatuser.first_name }}</td>  </tr>
 <tr> <th>last_name  </th> <td>{{ thatuser.last_name }}</td>  </tr>
 {% if user.is_superuser %}
  <tr> <th>email</th> <td>{{ thatuser.email }}</td>  </tr>
 {% endif %}
</table>

{% if email_form %}
<h2>Send email</h2>
<form role="form" action="{% url 'send_email' %}" method="post">
    {% csrf_token %}
    <table class="table table-bordered table-sm table-hover">
    {{ email_form.as_table }}
    </table>
    <button type="submit">Submit</button>
</form>
{% endif %}{# user.email #}

{% endblock %}